from types import CodeType
from typing import Any

def configure(codes: tuple[CodeType, ...], /) -> None: ...
def stats() -> list[tuple[int, int, int, int, float, float]]: ...
def py_start_callback(code: CodeType, instruction_offset: int, /) -> Any: ...
def py_resume_callback(code: CodeType, instruction_offset: int, /) -> Any: ...
def py_throw_callback(
    code: CodeType, instruction_offset: int, exception: BaseException, /
) -> None: ...
def py_yield_callback(
    code: CodeType, instruction_offset: int, retval: Any, /
) -> Any: ...
def py_return_callback(
    code: CodeType, instruction_offset: int, retval: Any, /
) -> Any: ...
def py_unwind_callback(
    code: CodeType, instruction_offset: int, exception: BaseException, /
) -> None: ...
